apiVersion: v1
kind: ServiceAccount
metadata:
  name: game-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: game-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["create", "delete", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: game-role-binding
subjects:
  - kind: ServiceAccount
    name: game-sa
    namespace: default
roleRef:
  kind: Role
  name: game-role
  apiGroup: rbac.authorization.k8s.io
